global:
  scrape_interval: 15s

scrape_configs:
  - job_name: evidenceprovider
    metrics_path: /metrics
    static_configs:
      - targets:
          - '34.7.214.206:8080'
          - '34.158.65.214:8080'
          - '34.12.85.105:8080'

  - job_name: evidenceverifier
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:8081'
